<?php

/**
 * ProcessWire Mark External Links
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class TextformatterMarkExternalLinks extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'Mark External Links', 
			'version' => 103, 
			'summary' => "Adds a class='external' and a rel='nofollow' to every external link."
		); 
	}

	public function format(&$str) {
		$str = preg_replace_callback('%<(a\s[^>]+)>%isU', array($this,"mark_external"), $str);
	}
	
	function mark_external($match) { 
	    list($original, $tag) = $match;  
	    if(preg_match('%\srel=(\'|")?[^\1]*nofollow(\s|\1|$)%i', $tag)) {
	        return $original;
	    }
	    $host = preg_quote($this->config->httpHost, "%");
	    $root = $this->config->urls->root ? preg_quote(rtrim($this->config->urls->root ,"/"), "%") : "";
	    if(preg_match('%\shref=(\'|")?(?:[\.]+|(?:https?:)?//'.$host.$root.'|(?!//)'.$root.')(?:/|\1|\?|#|\s|$)%is', $tag)) {
	        return $original;
	    }
	    return "<$tag rel='nofollow' class='external'>";
	}

}
